ebi-ait/hca-ebi-wrangler-central#702 stuck submission investigation and resolution steps
ebi-ait/hca-ebi-dev-team pull request #481
Opened 2022-03-24 11:33 UTC by prabh-t

2022-03-24 11:37 UTC, aaclan-ebi approved these changes
I would prefer correct capitalisation, but it's no biggie.

2022-03-24 11:37 UTC, aaclan-ebi commented on docs/operations_tasks/stuck-submissions.md
> +Steps to tourbleshoot:
```suggestion
Steps to troubleshoot:
```

2022-03-24 11:37 UTC, aaclan-ebi commented on docs/operations_tasks/stuck-submissions.md
> +Steps to tourbleshoot:
outdated, pls ignore

2022-03-30 13:39 UTC, amnonkhen requested changes

2022-03-30 15:49 UTC, amnonkhen approved these changes

2022-04-10 18:34 UTC, merged